robot_names:
  # - 'barrett'
  # - 'allegro'
  # - 'shadowhand'
  # - 'omnihand'
  - 'wujihand'

debug_object_names: null  # use part of the dataset, for debug only

# batch_size: 8  # 1 batch_size ≈ 4 GB GPU memory during training
# num_workers: 16
batch_size: 3
num_workers: 6
object_pc_type: 'random'  # 'fixed', 'random', 'partial'